function SellAnim(ped, target)
    TaskTurnPedToFaceEntity(ped, target, -1)
    TaskTurnPedToFaceEntity(target, ped, -1)
    while GetIsTaskActive(ped, 225) or GetIsTaskActive(target, 225) do Wait(100) end
    FreezeEntityPosition(ped, true)
    FreezeEntityPosition(target, true)
    TaskStandStill(target, 5000)
    SetPedAnim(target, "amb@world_human_smoking@male@male_a@enter","enter", 2000)
    Wait(1000)
    SetPedAnim(ped, "mp_common","givetake1_a", 1800)
    Wait(1000)
    SetPedAnim(ped, "amb@world_human_smoking@male@male_a@enter","enter", 2000)
    Wait(1000)
    SetPedAnim(target, "mp_common","givetake1_a", 1800)
    Wait(1000)
    FreezeEntityPosition(ped, false)
    FreezeEntityPosition(target, false)
    ClearPedTasks(ped)
end

function CallAnim(target)
    local heading = GetEntityHeading(target)
    -- SetEntityHeading(target, heading-180.0)
    SetPedAnim(target, "gestures@m@standing@casual","gesture_no_way", 1000)
    Wait(2000)
    local coords = GetEntityCoords(target)
    local phone = CreateObject(GetHashKey('prop_npc_phone_02'), coords.x, coords.y, coords.z+0.9,  true,  true, true)
    AttachEntityToEntity(phone, target, GetPedBoneIndex(target, 28422), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, true, true, false, true, 1, true)
    SetPedAnim(target, "cellphone@","cellphone_call_listen_base", 5000)
    Wait(5000)
    DetachEntity(phone, 1, 1)
	DeleteObject(phone)
end